-- Add 3 St. Lucia Marinas: Soufrière, Jalousie (Sugar Beach), Canaries
-- Data source: https://ports.marinelink.com/ports?search=st+lucia

-- 1. SOUFRIÈRE MARINA
INSERT INTO marina_profiles (
  name,
  slug,
  location,
  address,
  phone,
  website,
  website_label,
  latitude,
  longitude,
  boat_size_capacity,
  total_berths,
  mooring_ball_availability,
  restrooms_showers,
  water_depth,
  fuel_dock,
  water_availability,
  power_connections,
  maintenance_repair,
  chandlery,
  wifi,
  amenities,
  customs_hours_structured,
  immigration_hours_structured,
  clearance_notes,
  marinelink_url,
  status,
  created_at,
  updated_at
) VALUES (
  'Soufrière Marina',
  'soufriere',
  'Soufrière, St. Lucia',
  'Soufrière, St. Lucia, West Coast',
  'Contact local operators',
  'Not available',
  'Visit local tourism office',
  13.8539,
  -61.0623,
  'Yachts and smaller vessels',
  NULL,
  'Mooring balls available',
  'Restrooms and showers available',
  'Not specified',
  'Diesel and gasoline available',
  'Water connections available',
  'Electricity connections available',
  'Basic boat maintenance and repair',
  'Provisions and supplies nearby',
  'Wi-Fi access available',
  '["dining options", "shops and markets", "hotels", "dive shops", "snorkeling tours", "near the Pitons", "Sulphur Springs access", "Diamond Falls"]'::jsonb,
  '{"mon_fri": {"open": "08:00", "close": "16:00"}}'::jsonb,
  '{"mon_fri": {"open": "08:00", "close": "16:00"}}'::jsonb,
  'Tourist marina near iconic Pitons. Contact local operators for services.',
  'https://ports.marinelink.com/ports/port/soufriere',
  'approved',
  NOW(),
  NOW()
),

-- 2. JALOUSIE (SUGAR BEACH) MARINA
(
  'Jalousie Marina (Sugar Beach)',
  'jalousie',
  'Jalousie, Soufrière, St. Lucia',
  'Sugar Beach, Val des Pitons, Soufrière, St. Lucia',
  'Contact resort',
  'Not available',
  'Sugar Beach Viceroy Resort',
  13.8246,
  -61.0681,
  'Contact marina for vessel restrictions',
  NULL,
  'Limited berths - contact marina',
  'Resort facilities with showers',
  'Not specified - contact marina',
  'Fuel services available',
  'Freshwater hookups available',
  'Electricity hookups available',
  'Basic marine services (cleaning, minor repairs)',
  'Concierge services available',
  'Resort Wi-Fi and internet',
  '["resort access", "high-end dining", "water sports", "scuba diving", "snorkeling", "sailing", "fishing", "white sand beach", "spa facilities", "24/7 security", "between the Pitons"]'::jsonb,
  '{"mon_fri": {"open": "08:00", "close": "17:00"}}'::jsonb,
  '{"mon_fri": {"open": "08:00", "close": "17:00"}}'::jsonb,
  'Luxury resort marina between the Pitons. Limited berths - advance booking recommended.',
  'https://ports.marinelink.com/ports/port/jalousie',
  'approved',
  NOW(),
  NOW()
),

-- 3. CANARIES MARINA
(
  'Canaries Marina',
  'canaries',
  'Canaries, St. Lucia',
  'Canaries Fishing Village, Western Coast, St. Lucia',
  'Contact local operators',
  'Not available',
  'Visit local tourism office',
  13.9077,
  -61.0676,
  'Various vessel sizes accommodated',
  NULL,
  'Not specified',
  'Modern docking amenities',
  'Not specified',
  'Fuel services available',
  'Fresh water supply available',
  'Shore power connections available',
  'Boat maintenance and repairs',
  'Provisioning and supplies',
  'Wi-Fi connectivity available',
  '["24/7 security", "near Soufrière", "near the Pitons", "Anse Chastanet beach access", "snorkeling", "diving", "rainforest hiking", "Diamond Botanical Gardens", "Sulphur Springs"]'::jsonb,
  '{"mon_fri": {"open": "08:00", "close": "16:00"}}'::jsonb,
  '{"mon_fri": {"open": "08:00", "close": "16:00"}}'::jsonb,
  'Fishing village marina on west coast. Gateway to Soufrière and Pitons attractions.',
  'https://ports.marinelink.com/ports/port/canaries',
  'approved',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  updated_at = NOW();

-- Add initial vessel counts for all three marinas
INSERT INTO vessel_counts (location, count, recorded_at, time_of_day, reporter)
VALUES
  ('soufriere', 0, NOW(), 'morning', 'system'),
  ('jalousie', 0, NOW(), 'morning', 'system'),
  ('canaries', 0, NOW(), 'morning', 'system')
ON CONFLICT DO NOTHING;
