-- Add 7 Grenada Marinas (Full-Service Facilities)
-- Data source: Individual marina websites + MarineLink.com
-- Scraped: 2026-02-15

-- 1. GRENADA MARINE
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Grenada Marine', 'grenada-marine', 'St. David''s, Grenada',
  'La Chaussée Road, St David''s, Grenada', '+1 473-443-1667', 'https://grenadamarine.com', 'grenadamarine.com',
  12.0222, -61.6783,
  'Protected harbor', NULL, 'Yachts up to 150+ capacity',
  'Not available', 'Available', 'Available', 'Available', NULL,
  'Available', 'Complete maintenance, repairs, and refits', 'Available',
  '["70-ton travelift", "150+ yacht storage capacity", "secure boat storage", "bottom work", "topside respray", "10 acres beachfront facility", "authorized service centers (Volvo Penta, Yanmar, Northern Lights, Raymarine, Mastervolt)"]'::jsonb,
  '{"boat_sales": "New and project vessels", "email": "customerservice@grenadamarine.com", "office_hours": "Monday-Friday: 8:00 AM - 4:00 PM"}'::jsonb,
  'Family-owned operation with approximately 80 employees. Full-service boatyard.',
  'https://ports.marinelink.com/ports/grenada-marine', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();

-- 2. PRICKLY BAY MARINA
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Prickly Bay Marina', 'prickly-bay', 'L''Anse Aux Épines, Grenada',
  'L''Anse Aux Épines Road, St. George''s, Grenada', '+1 (473) 439-5265', 'https://pricklybaymarina.com', 'pricklybaymarina.com',
  11.9983, -61.7661,
  '18 feet max draft', NULL, '2 superyacht stern-to berths',
  'Duty-free fuel', 'Available', '3 phase 100A', 'Available', NULL,
  'Available', 'Available', 'Available',
  '["restaurant", "café", "tiki bar", "live music", "daily sundowner happy hour (1700 hours)", "waterside apartment rentals", "24-hour security", "port of entry"]'::jsonb,
  '{"customs_immigration": "Onsite, 7 days/week", "agency_services": "Clearance assistance available", "email": "info@pricklybaymarina.com", "office_hours": "Mon-Fri: 7:30 AM - 12:00 PM, Sat-Sun: 8:30 AM - 12:00 PM"}'::jsonb,
  'Port of entry for clearing in/out. Customs and Immigration onsite 7 days/week.',
  'https://ports.marinelink.com/ports/prickly-bay', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();

-- 3. SPICE ISLAND MARINE SERVICES
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Spice Island Marine Services', 'spice-island', 'True Blue, Grenada',
  'P.O. Box 449, True Blue Avenue, St. George''s, Grenada', '+1 (473) 444-4342', 'https://www.spiceislandmarine.com', 'spiceislandmarine.com',
  12.0011, -61.7684,
  'Max beam 25 feet, length 85 feet', NULL, 'Vessels up to 85 feet',
  'Diesel available', 'Available', 'Available', 'Available', '16',
  'Available', 'Full service including Awlgrip, osmosis, bottom painting', 'Budget Marine Duty Free Chandlery',
  '["70-ton Marine Travelift", "long term dry storage", "full service sail loft", "Bianco Blu Italian restaurant", "bar", "24-hour security"]'::jsonb,
  '{"customs_brokerage": "Available", "caretaking": "Available", "email": "simsco@spiceislandmarine.com"}'::jsonb,
  'Grenada''s first full-service marina. Family-owned business with over four decades of marine mastery.',
  'https://ports.marinelink.com/ports/spice-island-marine', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();

-- 4. SECRET HARBOUR MARINA
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Secret Harbour Marina', 'secret-harbour', 'Lance aux Epines, Grenada',
  'Lance aux Epines, P.O Box 1362 Grand Anse, St George''s, Grenada', '+1 (473) 444-4449', 'https://www.secretharbourgrenada.com', 'secretharbourgrenada.com',
  12.0088, -61.7550,
  'Protected harbor', 53, 'Various vessel sizes',
  'Not available', 'Available', 'Available', 'Free WiFi', '16/68',
  'Available', 'Available', 'Available',
  '["53 marina berths", "20 boutique hotel cottages", "restaurant & bar", "gym with marina views", "swimming pool", "spa and hair salon", "Secret Radio 92.7 FM", "concierge services"]'::jsonb,
  '{"whatsapp": "+1 (473) 405-2884 (available 24/7)", "security": "+1 (473) 405-2529", "restaurant": "+1 (473) 435-4439", "fax": "+1 (473) 444-2090", "email": "enquiries@secretharbourgrenada.com", "office_hours": "Monday-Saturday: 8:00 AM - 5:30 PM, Sunday: 9:00 AM - 4:00 PM (Available 24/7 via WhatsApp)"}'::jsonb,
  '7 hectares property in Mount Hartman Bay, 15 minutes from Maurice Bishop International Airport.',
  'https://ports.marinelink.com/ports/secret-harbour', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  total_berths = EXCLUDED.total_berths,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();

-- 5. CLARKE'S COURT BOATYARD & MARINA
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Clarke''s Court Boatyard & Marina', 'clarkes-court', 'Woburn, Grenada',
  'Clarkes Court Bay Road, Woburn, St. George, Grenada', '+1 (473) 439-3939', 'https://www.clarkescourtmarina.com', 'clarkescourtmarina.com',
  12.0003, -61.7453,
  'Deep water for large vessels', NULL, 'Large multihulls, motor and sailing yachts, commercial vessels',
  'Not available', 'Available', 'Available', 'Available', '16/74 (also 68/11)',
  'Showers available', 'Routine maintenance and major refit projects', 'Available',
  '["242-ton Travelift", "32-ton submersible trailer", "bar and restaurant", "laundry services", "tender personnel for line handling", "shuttle service to Woburn dock"]'::jsonb,
  '{"whatsapp": "+1 (473) 423-1222", "fax": "+1 (473) 439-3940", "email": "info@clarkescourtmarina.com", "approved_contractors": "Technical service contractors available"}'::jsonb,
  'Capacity for large vessels with 242T Travelift and 32T submersible trailer.',
  'https://ports.marinelink.com/ports/clarkes-court', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();

-- 6. CARRIACOU MARINE
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Carriacou Marine', 'carriacou-marine', 'Tyrrel Bay, Carriacou',
  'South west side of Tyrrel Bay, Carriacou, Grenada', '+1 (473) 443-6292', 'https://carriacoumarine.com', 'carriacoumarine.com',
  12.4533, -61.4872,
  'Boats up to 70 feet, 18-foot beam', NULL, 'Vessels up to 70 feet',
  'Duty-free fuel (gasoline and diesel via SOL)', 'Available', 'Available', 'Complimentary Wi-Fi', '16/68',
  'Available', 'Full boatyard services', 'Island Water World chandlery, convenience store',
  '["40-ton ASCOM travel lift", "The Iguana Café (breakfast, lunches, pizza nights, grilled seafood)", "on-site cottage accommodation", "55\" satellite TV", "port of entry/exit"]'::jsonb,
  '{"whatsapp": "+1 (473) 406-0314", "email": "[email protected]", "customs_immigration": "Customs and immigration processing available", "office_hours": "Fuel station: Mon-Sat: 08:00-17:30, Sun/holidays: 08:00-14:00, Café: All day service"}'::jsonb,
  'First port of entry/exit for vessels arriving from the north. 15-minute taxi ride from Lauriston airport or Osprey ferry dock.',
  'https://ports.marinelink.com/ports/carriacou', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();

-- 7. PORT LOUIS MARINA
INSERT INTO marina_profiles (
  name, slug, location, address, phone, website, website_label,
  latitude, longitude,
  water_depth, total_berths, boat_size_capacity,
  fuel_dock, water_availability, power_connections, wifi, vhf_channel,
  restrooms_showers, maintenance_repair, chandlery,
  amenities, additional_services,
  clearance_notes, marinelink_url, status,
  created_at, updated_at
) VALUES (
  'Port Louis Marina', 'port-louis', 'St. George''s, Grenada',
  'Kirani James Boulevard, St. George''s, Grenada', '+1 (473) 435-6661', 'https://cnmarinas.com/marinas/port-louis-marina/', 'Port Louis Marina',
  12.0547, -61.7523,
  'Up to 300 feet vessels', 160, 'Yachts up to 300 feet',
  'Duty free fuel and oil', 'Available', 'Available', 'Wireless broadband', '14',
  'Shower and laundry', 'Boat maintenance services available', 'Available',
  '["160 berths", "cable TV", "grey and black water discharge", "refuse disposal", "provisioning", "yacht services", "parts ordering and courier services", "airport transfers", "car rentals", "excursions", "Victory Bar & Grill", "sail-maker", "shops for leisure wear and crafts", "24 hour CCTV and night security", "official port of entry"]'::jsonb,
  '{"phone_alt": "+1 (473) 435-7432", "customs_immigration": "Customs and Immigration facility - official port of entry", "operator": "Owned and operated by Camper & Nicholsons Marinas", "office_hours": "Base hours: 7 days/week: 08:00-17:00, Capitainerie: Daily: 07:00-19:00"}'::jsonb,
  'Located in the Lagoon on the outskirts of St. George''s, overlooking the Carenage. Premier full-service marina.',
  'https://ports.marinelink.com/ports/port-louis', 'approved', NOW(), NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  website_label = EXCLUDED.website_label,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  water_depth = EXCLUDED.water_depth,
  total_berths = EXCLUDED.total_berths,
  boat_size_capacity = EXCLUDED.boat_size_capacity,
  fuel_dock = EXCLUDED.fuel_dock,
  water_availability = EXCLUDED.water_availability,
  power_connections = EXCLUDED.power_connections,
  wifi = EXCLUDED.wifi,
  vhf_channel = EXCLUDED.vhf_channel,
  restrooms_showers = EXCLUDED.restrooms_showers,
  maintenance_repair = EXCLUDED.maintenance_repair,
  chandlery = EXCLUDED.chandlery,
  amenities = EXCLUDED.amenities,
  additional_services = EXCLUDED.additional_services,
  clearance_notes = EXCLUDED.clearance_notes,
  marinelink_url = EXCLUDED.marinelink_url,
  status = EXCLUDED.status,
  updated_at = NOW();
